workflows:
  android-native-workflow:
    name: Android Native Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.aaryan7.dastakmobile7"
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - n- name: Build Android app
  script: |
    cd $CM_BUILD_DIR
    chmod +x ./gradlew
    ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - myuse077@gmail.com
        notify:
          success: true
          failure: true
